### ISSUE TITLE
Licencja kodu

### ISSUE THREAD

**Issue by gszy** [jendrusk/osm_report_addr#5]

**Comment by jendrusk** [comment]
CC-BY-SA(-NC)?
Dowolna wolna... być może z wykluczeniem użycia komercyjnego?
Ale jestem otwarty na propozycje.

**Comment by gszy** [comment]
Na CC zbyt wiele kodu nie widziałem. Ja bym wybrał BSD lub MIT (pewnie dlatego, że innych dość dobrze nie znam :expressionless:).

No i to repozytorium chyba zawiera kod z wcześniejszych projektów, więc dobrze by było o to zapytać innych autorów.

**Comment by jendrusk** [comment]
Pomijając wciągane moduły reszta kodu jest w całości moja.
A z kim gadam wogóle? Bo nick mi nic nie mówi :)

**Comment by gszy** [comment]
> A z kim gadam wogóle? Bo nick mi nic nie mówi :)

https://www.openstreetmap.org/user/gscscnd albo `git log`

**Comment by matkoniecz** [comment]
https://choosealicense.com/

**Comment by jendrusk** [comment]
Dzięki Mateusz.

Chyba nie ma sensu wydziwiać i trzeba zrobić MIT.

**Comment by jendrusk** [comment]
To mamy wybrane. Dopiszcie proszę gdzie trzeba
