### ISSUE TITLE
Zmiana podejścia - statyczne raporty html- konsultacja

### ISSUE THREAD

**Issue by jendrusk** [jendrusk/osm_report_addr#7]
Tak mi wyszło w trakcie, że chyba lepiej byłoby trochę zmienić podejście - w komentarzu do changeseta podac tylko minimalne informacje - że powstały uszkodzone adresy i że więcej info w raporcie (link). Watcher będzie generował statyczne raporty dla changesetów w html i wyhostuję je apachem na serwerze (lub bardziej ładnie i dynamicznie - zapiszę do bazy i wyhostuję flaskiem).
Dlaczego:
1. W ten sposób mniej śmiecimy w bazie OSM - komentarze będą krótsze
2. Mamy większą uniwersalność - w komentarzu nie użyjemy html więc nie da się zrobić linków do obiektu czy do JOSM
3. Przy hostowaniu flaskiem (lub nawet z logów apache) możemy wyciągnąć informacje czy była jakaś reakcja na komentarz.
Co myślicie?

**Comment by matkoniecz** [comment]
> więc nie da się zrobić linków do obiektu

da się. linki wstawione zwykłym testem linkują patrz np. https://www.openstreetmap.org/changeset/60252261

Inne linki też działają - np. https://www.openstreetmap.org/changeset/61030785

Choć jest oczywiście pewne ryzyko że w wyniku spamu zostanie to ograniczone w przyszłości (ale linki do OSM wiki i obiektów OSM pewnie będą działać)

> możemy wyciągnąć informacje czy była jakaś reakcja na komentarz.

A to spory plus jeśli da się to zrobić

Dodatkowo, taka strona byłaby pomocna dla sprzątających - można łatwo obejrzeć wszystkie problemy danego typu.

**Comment by jendrusk** [comment]
Tak, wstawiony link podświetli, ale jak ktoś w jednym changesecie zrobi 50 błędów (np import) to wstawimy w komentarz 50 linków - będzie brzydko...
Dodatkowo Takie podejście pozwoli nam na opóźnienie - raport można będzie odpalać np. co godzinę, będzie wyświetlał informacje na stronie (i tylko tam) a komentarze można będzie dodawać dla obiektów starszych niż x - czyli np. nie poprawionych przez 3 dni od utworzenia...
Tak sobie myślę...

> A to spory plus jeśli da się to zrobić

Przy hostowaniu flaskiem żaden problem

**Comment by gszy** [comment]
Przy takim linkowaniu do zewnętrznych raportów trzeba jeszcze uwzględnić to, że użytkownik może chcieć uruchomić projekt lokalnie (chyba, że takich nie przewidujemy). W takim przypadku komentarze zawierałyby nieosiągalne linki, więc chyba nie należałoby ich w ogóle dodawać?

**Comment by jendrusk** [comment]
To nie będą zewnętrzne raporty.
Mnie wychodzi że trzeba by zrobić tak:
1. Istniejący kod przekształcić w updater - cała jego funkcjonalność zamknie się do pobrania raportu uszkodzonych, zwalidowania go (to już robi) i zapisania do jakiejś lokalnej bazki (sqlite wystarczy).
2. Dopiszemy drugą część na flasku, która z tej bazy sqlite będzie serwowała prostą stronę z raportem (wykaz changesetów i szczegóły changesetu)
3. Cześć kodu przeniesiemy do commentera, który po odpaleniu przejrzy obiekty i jeśli są nadal niepoprawne okomentuje changesety w których powstały
Rozwiązanie jest spójne i poza źródłem raportów (baza osm2pgsql) nie ma zewnętrznych zależności.

**Comment by gszy** [comment]
> poza źródłem raportów (baza osm2pgsql) nie ma zewnętrznych zależności.

Ale będzie tworzyć nowe komentarze. I według tego:

> że powstały uszkodzone adresy i że więcej info w raporcie (link)

w komentarzach byłyby (może opcjonalne?) linki do raportów.

**Comment by jendrusk** [comment]
Można je zrobić jako opcję ale jednym z zarzutów do istniejącego softu jest to, że komentarz jest zbyt ogólny i nie wskazuje wprost na obiekt w którym jest błąd, jak również nie opisuje na czym ten błąd polega.

**Comment by jendrusk** [comment]
Sory, się mi zamknęło przypadkiem

**Comment by jendrusk** [comment]
Zamykam - to podejście ma więcej plusów więc tak napisałem...
