### ISSUE TITLE
Oparcie rozwiązania o overpass

### ISSUE THREAD

**Issue by jendrusk** [jendrusk/osm_report_addr#8]
Tak się zastanawiam...
Aktualne rozwiązanie opiera się o bazę danych, ale nie każdy ma, nie wszędzie jest, pozatym to działa jeśli masz bazę i tak do innych zastosowań - tworzenie i synchronizowanie bazy osm2pgsql tylko dla tego rozwiązania jest bez sensu...
Dlatego, żeby zwiększyć uniwersalność rozwiązania może byśmy spróbowali oprzeć to o overpassAPI?

@matkoniecz  jesteś specem od overpassa jak dobrze pamiętam - mógłbyś spróbować napisać funkcję która zwróci taką listę?:

<class 'list'>: [{'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 1408452758, 'reason': 'nc_np_s', 'type': 'node', 'version': '2', 'lat': 52.1827609684961, 'lon': 21.5573657667594}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 1434191108, 'reason': 'nc_np_s', 'type': 'node', 'version': '2', 'lat': 52.1813369694001, 'lon': 21.5485674872036}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 2092307813, 'reason': 'nc_np_s', 'type': 'node', 'version': '3', 'lat': 52.1810084070677, 'lon': 21.5696344179207}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 2092307821, 'reason': 'nc_np_s', 'type': 'node', 'version': '4', 'lat': 52.1809261697119, 'lon': 21.5695807884982}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 2099458637, 'reason': 'nc_np_s', 'type': 'node', 'version': '2', 'lat': 52.1809419782442, 'lon': 21.5540633801119}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 2193074748, 'reason': 'nc_np_s', 'type': 'node', 'version': '3', 'lat': 52.1801399773205, 'lon': 21.5614799609291}, {'user': 'grelus', 'changeset': '61022903', 'osm_id': 3164346804, 'reason': 'c_p_ns', 'type': 'node', 'version': '2', 'lat': 52.8961821036467, 'lon': 14.4613887337084}, {'user': 'user_5359', 'changeset': '61023267', 'osm_id': 4312237122, 'reason': 'nc_np_s', 'type': 'node', 'version': '4', 'lat': 50.0675869038088, 'lon': 19.9335794135171}, {'user': 'rezerwa', 'changeset': '61024975', 'osm_id': 5781864561, 'reason': 'c_np_ns', 'type': 'node', 'version': '1', 'lat': 50.8437006648419, 'lon': 20.8616928037576}, {'user': 'JulesGabrielVerne', 'changeset': '61025419', 'osm_id': 757517164, 'reason': 'nc_np_s', 'type': 'node', 'version': '2', 'lat': 53.4207309908061, 'lon': 14.5603280112914}, {'user': 'Patryk Eliasz', 'changeset': '61026071', 'osm_id': 5781949170, 'reason': 'c_np_ns', 'type': 'node', 'version': '1', 'lat': 50.7223152002732, 'lon': 19.7584811458094}, {'user': '( ͡° ͜ʖ ͡°)', 'changeset': '61030511', 'osm_id': 2272504512, 'reason': 'c_p_ns', 'type': 'node', 'version': '2', 'lat': 54.5854675852109, 'lon': 16.9728231465659}, {'user': '( ͡° ͜ʖ ͡°)', 'changeset': '61030511', 'osm_id': 2272506627, 'reason': 'c_p_ns', 'type': 'node', 'version': '2', 'lat': 54.5853434828411, 'lon': 16.9724208809816}, {'user': 'StalkerOSM', 'changeset': '61035404', 'osm_id': 5333118457, 'reason': 'nc_np_s', 'type': 'node', 'version': '4', 'lat': 50.8431292901071, 'lon': 16.4190959460483}, {'user': 'Misiek_J', 'changeset': '61044795', 'osm_id': 364475860, 'reason': 'nc_np_s', 'type': 'way', 'version': '2', 'lat': 49.9804308211257, 'lon': 18.4959496845416}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 300695394, 'reason': 'nc_np_s', 'type': 'way', 'version': '5', 'lat': 52.177263552972, 'lon': 21.5737182057652}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 300695347, 'reason': 'nc_np_s', 'type': 'way', 'version': '5', 'lat': 52.1771469169831, 'lon': 21.575058191743}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 200164924, 'reason': 'nc_np_s', 'type': 'way', 'version': '4', 'lat': 52.1772581024864, 'lon': 21.5502510340725}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 199962713, 'reason': 'nc_np_s', 'type': 'way', 'version': '4', 'lat': 52.1826514220842, 'lon': 21.5561097410871}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 199962567, 'reason': 'nc_np_s', 'type': 'way', 'version': '5', 'lat': 52.1812119545077, 'lon': 21.5539675295676}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 199206955, 'reason': 'nc_np_s', 'type': 'way', 'version': '5', 'lat': 52.1809548991875, 'lon': 21.5696224234481}, {'user': 'Piotr Strębski', 'changeset': '61009995', 'osm_id': 130125188, 'reason': 'nc_np_s', 'type': 'way', 'version': '2', 'lat': 52.1790755547055, 'lon': 21.5572966027392}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364476764, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9799499598665, 'lon': 18.5032597451677}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364476714, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9808811964417, 'lon': 18.5037540491066}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364476307, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9803796785492, 'lon': 18.5031778958262}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364476145, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9785107215603, 'lon': 18.5022322684695}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364475962, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9805608319142, 'lon': 18.5034071580208}, {'user': 'maraf24', 'changeset': '61012295', 'osm_id': 364475895, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9787903889779, 'lon': 18.5022601555105}, {'user': 'Ciorcyk', 'changeset': '61011287', 'osm_id': 356675996, 'reason': 'nc_p_s', 'type': 'way', 'version': '4', 'lat': 50.1826035425311, 'lon': 19.9313640374808}, {'user': 'Ciorcyk', 'changeset': '61013353', 'osm_id': 323649633, 'reason': 'c_p_s', 'type': 'way', 'version': '3', 'lat': 50.1794050726599, 'lon': 19.9201373108091}, {'user': 'gscscnd', 'changeset': '61013266', 'osm_id': 364476208, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9828900974687, 'lon': 18.503551695936}, {'user': 'gscscnd', 'changeset': '61013266', 'osm_id': 364475915, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9827733340664, 'lon': 18.5033345924435}, {'user': 'gscscnd', 'changeset': '61013266', 'osm_id': 364475853, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.9855180117653, 'lon': 18.5046421681589}, {'user': 'gscscnd', 'changeset': '61013266', 'osm_id': 364475835, 'reason': 'nc_np_s', 'type': 'way', 'version': '3', 'lat': 49.985772636607, 'lon': 18.5044955335595}, {'user': 'mackerski', 'changeset': '61017896', 'osm_id': 480347749, 'reason': 'nc_np_s', 'type': 'way', 'version': '2', 'lat': 54.3564756809808, 'lon': 18.652586382014}, {'user': 'rezerwa', 'changeset': '61024888', 'osm_id': 353018712, 'reason': 'c_np_ns', 'type': 'way', 'version': '2', 'lat': 50.8436664253931, 'lon': 20.8617601247901}, {'user': 'Patryk Eliasz', 'changeset': '61026071', 'osm_id': 610551520, 'reason': 'c_np_ns', 'type': 'way', 'version': '1', 'lat': 50.7222760870069, 'lon': 19.7584781085822}, {'user': 'JulesGabrielVerne', 'changeset': '61031440', 'osm_id': 59448766, 'reason': 'nc_np_ns', 'type': 'way', 'version': '3', 'lat': 53.4907180950323, 'lon': 14.4808461548832}, {'user': 'rezerwa', 'changeset': '61031039', 'osm_id': 353019072, 'reason': 'c_np_ns', 'type': 'way', 'version': '2', 'lat': 50.8432272164365, 'lon': 20.8619104484924}, {'user': 'rezerwa', 'changeset': '61031342', 'osm_id': 167863333, 'reason': 'c_np_ns', 'type': 'way', 'version': '3', 'lat': 50.8425200524069, 'lon': 20.8628401300661}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620016, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.4111092528763, 'lon': 21.9901185708771}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 515364959, 'reason': 'nc_np_s', 'type': 'way', 'version': '2', 'lat': 51.4074371095987, 'lon': 21.9986707980611}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 515364857, 'reason': 'nc_np_s', 'type': 'way', 'version': '2', 'lat': 51.4111785833102, 'lon': 21.9896279097008}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 333774749, 'reason': 'nc_np_s', 'type': 'way', 'version': '4', 'lat': 51.4079299840141, 'lon': 22.0035630004952}, {'user': 'rezerwa', 'changeset': '61034898', 'osm_id': 353321369, 'reason': 'c_p_ns', 'type': 'way', 'version': '3', 'lat': 50.8554210302979, 'lon': 20.8255647128778}, {'user': 'rezerwa', 'changeset': '61035495', 'osm_id': 352837760, 'reason': 'c_np_ns', 'type': 'way', 'version': '2', 'lat': 50.8483750593017, 'lon': 20.8218457682519}, {'user': 'rezerwa', 'changeset': '61035495', 'osm_id': 352837521, 'reason': 'c_np_ns', 'type': 'way', 'version': '2', 'lat': 50.8481561574626, 'lon': 20.821790588589}, {'user': 'rezerwa', 'changeset': '61035658', 'osm_id': 353320379, 'reason': 'c_p_ns', 'type': 'way', 'version': '4', 'lat': 50.880137897271, 'lon': 20.8500134655923}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620173, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.4085540195908, 'lon': 21.997215595839}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620143, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.4109684893768, 'lon': 21.9903483801956}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620122, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.4108606352266, 'lon': 21.9897002974244}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620112, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.4104074099664, 'lon': 21.9902815997664}, {'user': 'Eye1024', 'changeset': '61034420', 'osm_id': 610620108, 'reason': 'nc_np_s', 'type': 'way', 'version': '1', 'lat': 51.407740151763, 'lon': 21.9982941990918}]

Warunki tworzenia można wywnioskować z sql-a

**Comment by matkoniecz** [comment]
> mógłbyś spróbować napisać funkcję która zwróci taką listę

Jakieś preferencje w czym ta funkcja ma być? Może teoretycznie da sie to zrobić jednym zapytaniem w Overpassie - ale byłoby to monstrum koszmarne to napisania, nawet jeśli jest to możliwe.

Najprościej byłoby mi to zrobić w Rubym (lub Pythonie), kilkoma osobnymi zapytaniami do overpassa + trochę kodu do przetworzenia danych.

Da sie to zrobić też w innych językach, ale wtedy zajmie mi to trochę więcej czasu (mam już kod który komunikuje się z Overpassem w Rubym i trochę prymitywniejszą wersję robiącą to w Pythonie).

**Comment by jendrusk** [comment]
Całość jest w Pythonie więc chyba najlepiej by było... ja bym użył requests. Optymalnie by było jakby się dało później dołożyć tu po prostu plik z Twoim kodem, zaimportować i podmienić jedną linijkę:

`rep = get_addr_rep()`

Nawet są jakieś gotowe wrappery, tylko czy zrobią to co potrzebujesz to do sprawdzenia:
https://www.google.com/search?q=overpass+api+python&ie=utf-8&oe=utf-8&client=firefox-b-ab
https://pypi.org/project/overpass/

**Comment by jendrusk** [comment]
Zrobiłem badania i mnie się nie udało. Overpass ma potrzebne funkcje ale nie radzi sobie z takimi zapytaniami - albo timeouty albo przekroczenie przydziału ramu. Można by podzielić obszar na składowe (np. pobierać każde województwo z osobna) ale i tak trwa to bardzo długo (~10 minut za województwo). Szukałem innych metod ale zaczyna się z tego robić pająk (np. osmosis, pobieranie diffów, parsowanie i pobieranie changesetów z API, odpytywanie o obiekty...)
Wychodzi, że chyba baza to najoptymalniejsze wyjście...
