### ISSUE TITLE
RailsPort nie ustawia nagłówka referer

### ISSUE THREAD

**Issue by jendrusk** [jendrusk/osm_report_addr#9]
Napisałem zapisywanie wizyt w raportach poszczególnych changesetów. Planowałem użyć nagłówka referer, żeby oddzielić wizyty z głównej listy (nasze, wewnętrzne, edytorów, którzy poprawiają) od wizyt przez link pozostawiony w changesecie... Niestety strona osm.org nie ustawia nagłówka referera (podczas gdy sami go jawnie wymagają w warunkach użycia kafelków)
Mateusz - Ty działasz jakoś bardziej światowo w OSM, wiesz kto jest kim... mógłbyś do kogoś uderzyć żeby go jednak ustawiali?
![obraz](https://user-images.githubusercontent.com/9802737/43370378-4dc9a4e8-937e-11e8-9b90-2bde4a8b556e.png)

**Comment by gszy** [comment]
W Chrome domyślna wartość [`Referrer-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) to `no-referrer-when-downgrade` (w Firefoksie chyba jest tak samo), czyli nie dostaniesz refer[r]era jeśli Twoja strona działa na HTTP (a poprzednia na HTTPS). Nie zauważyłem, żeby openstreetmap.org ustawiał jakąś swoją politykę refer[r]erów.

**Comment by jendrusk** [comment]
Widzisz - nie jestem w tym specjalistą, ale właśnie wydawało mi się że grzebanie przy refererach jest raczej trudne... dlatego mnie to dziwiło. To może być to. Zaniedługo będę wdrażał tę wersję jeszcze bez commentera żeby się już kręciła to wystawię ją po https i wtedy sprawdzę.

**Comment by matkoniecz** [comment]
> mógłbyś do kogoś uderzyć żeby go jednak ustawiali?

Zasadniczo bugi w stronie zgłasza się na https://github.com/openstreetmap/openstreetmap-website

Ale warto najpierw wyjaśnić czy to nie problem opisany przez @gscscnd
